# RAG System Configuration

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  embeddings_dir: "data/embeddings"

# Embedding settings
embeddings:
  model_name: "all-MiniLM-L6-v2"  # Default sentence transformer model
  chunk_size: 1000
  chunk_overlap: 200

# Vector store settings
vector_store:
  collection_name: "music_label_docs"
  persist_directory: "data/vector_store"

# Content generation settings
generation:
  max_tokens: 1000
  temperature: 0.7
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0

# Document processing
document_processing:
  supported_formats:
    - "txt"
    - "pdf"
    - "docx"
    - "md"
  max_file_size_mb: 10

# API settings
api:
  host: "localhost"
  port: 8000
  debug: true

# Logging
logging:
  level: "INFO"
  file: "logs/rag_system.log"
  max_size_mb: 10
  backup_count: 5 